[package]
name = "depot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.3"
base64 = "0.21.7"
pbkdf2 = "0.12.2"
rand = "0.8.5"
rusqlite = "0.30.0"
sha1 = "0.10.6"
termion = "3.0.0"
